spring:
  profiles:
    active: smart
    
  thymeleaf:
    cache: false
    
hr:
  employee:
    def:
      percent: 0
      
    smarts:
     -
      limit: 5
      percent: 5
     -
      limit: 2.5
      percent: 2
     -
      limit: 10
      percent: 10
