spring:
  profiles:
    active: smart
hr:
  employee:
    def:
      percent: 10
    smart:
      limit10: 10
      percent10: 10
      limit5: 5
      percent5: 5
      limit2: 2.5
      percent2: 2
